In [1]:

str ="hellothere , am happy"
substr = str[1:6:2]
print(substr)

elt


In [1]:
!pip install numpy
!pip install pandas

In [2]:
str ="hello there , am happy"
substr = str[1:6]
print(substr)

ello 


In [3]:
str ="hello there , am happy"
substr = str[6:]
print(substr)

there , am happy


In [4]:
str ="hellothere , am happy"
substr = str[1:6]
print(substr)

ellot


In [5]:
str ="hello there , am happy"
substr = str[:]
print(substr)

hello there , am happy


In [6]:
str.capitalize()

'Hello there , am happy'

In [7]:
str.count('e')

3

In [8]:
str .index('e')

1

In [9]:
str .split()

['hello', 'there', ',', 'am', 'happy']

In [1]:
#----print messages in python
print('introduction to python')
print('python is fun')



introduction to python
python is fun


In [2]:
#---compute an expression
print(10+20*3/2)

40.0


In [2]:
#graphics programming
#import turtle is used for graphics programming
# turtule refers to the object for drawin graphics
#defining a turtle
import turtle # Import turtle module


#direction of a turtle
turtle.showturtle()





In [8]:

#drawing a text line
turtle.write("Welcome to Python")

In [12]:
#move the arrowhead 100 pixels forward to draw a line in the direction the arrow is pointing
turtle.forward(50)

In [1]:
2+3

5

In [8]:
# outputs a float value
2/3


0.6666666666666666

In [2]:
#outputs an integer value
2//3

0

In [9]:
4/2

2.0

In [10]:
# power values
12**2

144

In [11]:
6**2

36

In [12]:
#outputs a reminder
5%2

1

In [13]:
2-3+2

1

In [14]:
#application of bodmas
2-(3+2)

-3

In [15]:
#printing out string statements
print('JOSEPHINE IS LEARNING PYTHON')

JOSEPHINE IS LEARNING PYTHON


In [16]:
#error is generated 
print('jose's laptop')

SyntaxError: unterminated string literal (detected at line 1) (4075368208.py, line 1)

In [17]:
#to solve error use the double and the single quotes
print("jose's laptop")

jose's laptop


In [37]:
#if u want to quote a certain word
print('jose "is smart"')

jose "is smart"


In [20]:
#use of a backslash
print('jose\'s "laptop"')

jose's "laptop"


In [22]:
#concatenation
print('jose' + 'jose')

josejose


In [29]:
#word spacing
print('jose' + ' ' + 'jose')

jose jose


In [30]:
print("jose" + " " + "jose")

jose jose


In [36]:
print('jose'+ ' ' + "is smart")

jose is smart


In [42]:
#raw string---printing c:\docs\jose put r
print( r'c:\docs\jose')

c:\docs\jose


In [43]:
print('c:\docs\jose')

c:\docs\jose


<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Jose\AppData\Local\Temp\ipykernel_7864\3851768091.py:1: SyntaxWarning: invalid escape sequence '\d'
  print('c:\docs\jose')


In [47]:
#printing jose multiple times but wen they are spaced
print(10*'jose' ' ')

jose jose jose jose jose jose jose jose jose jose 


In [62]:
#VARIABLES IN PYTHON
#Variable is a container that stores a value
x = 2
x + 2



4

In [66]:
y = 3
x + y

5

In [67]:
x = 4
x + y

7

In [69]:
name = 'youtube'
name

'youtube'

In [70]:
print(name)

youtube


In [71]:
name + 'rocks'

'youtuberocks'

In [72]:
name + ' ' + 'rocks'

'youtube rocks'

In [77]:
name 'rocks'

SyntaxError: invalid syntax (639239415.py, line 1)

In [74]:
#indexing
name[1]

'o'

In [75]:
name[-2]

'b'

In [76]:
name[1:2]

'o'

In [78]:
name[1:4]

'out'

In [83]:
#NUMPYNARRAY

import numpy as np 

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
my_arr


array([     0,      1,      2, ..., 999997, 999998, 999999])

In [91]:
#list of lists  of integers
lst = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
lst

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [93]:
np.array(lst)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
lst

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [94]:
lst

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [96]:
#shapes
data =np.array(lst)

In [97]:
data.shape

(3, 4)

In [98]:
#getting a datatype
arr2 = np.array([1,2,3],dtype = np.float64)
arr2

array([1., 2., 3.])

In [103]:
arr3 = np.array([1,2,3],dtype = np.complex128)
arr3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [105]:
arr3.astype(np.int8)


C:\Users\Jose\AppData\Local\Temp\ipykernel_7864\3033543015.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  arr3.astype(np.int8)


array([1, 2, 3], dtype=int8)

In [109]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
#Arithmetic With Numpy
arr = np.array([[1,2,3],[4,3,1]])
arr

array([[1, 2, 3],
       [4, 3, 1]])

In [111]:
arr * arr

array([[ 1,  4,  9],
       [16,  9,  1]])

In [112]:
arr + arr

array([[2, 4, 6],
       [8, 6, 2]])

In [113]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [114]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [115]:
arr^2

array([[3, 0, 1],
       [6, 1, 3]], dtype=int32)

In [116]:
arr **2

array([[ 1,  4,  9],
       [16,  9,  1]])

In [117]:
arr%arr

array([[0, 0, 0],
       [0, 0, 0]])

In [118]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.33333333, 1.        ]])

In [119]:
arr2 = np.array([[0.,4.,3.],[1,3,4]])
arr2

array([[0., 4., 3.],
       [1., 3., 4.]])

In [120]:
arr2 > arr

array([[False,  True, False],
       [False, False,  True]])

In [134]:
arr[0,0]

1

In [122]:
arr >= arr2

array([[ True, False,  True],
       [ True,  True, False]])

In [121]:
arr > arr2

array([[ True, False, False],
       [ True, False, False]])

In [123]:
arr3d = np.array([[[1,2,2],[3,4,5]],[[6,7,8],[9,10,11]]])
arr3d

array([[[ 1,  2,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [132]:
arr3d[0]

array([[1, 2, 2],
       [3, 4, 5]])

In [131]:
#multiple indexing
arr3d[1,0]

array([6, 7, 8])

In [136]:
arr3d[0,0,0]

1

In [138]:
arr3d[0,1,1]


4

In [139]:
arr3d[0,0,1]

2

In [140]:
arr3d[0,0,2]

2

In [143]:
arr3d[0,1,0]

3

In [2]:

#casting : specifing the data type of a variable
x = 2
print (type(x))
y = "string"
print (type(y))


<class 'int'>
<class 'str'>


In [5]:
# variables are case sensitive
a = 2
A = 3
print(A)

3


In [11]:
# Assing values to multiple variables
x,y,z = 2,3,4
print(x)
print(y)
print(z)

2
3
4


In [12]:
# assigning one value to multiple variables 
#Simultaneous assignment
x = y = z = 4
print(x)
print(y)
print(z)

4
4
4


In [17]:
#unpacking a collection
my_list = ["orange", "blue", "black"]
x, y, z = my_list
print(x)

print(y)

print(z)

orange
blue
black


In [20]:
# output variables

x = "python is fun"

print(x)

python is fun


In [22]:
x = "python"
y = "is"
z = "fun"
print(x,y,z)

python is fun


In [23]:
# using the + operator to form sentence without a space charcters after is and python
x = "python"
y = "is"
z = "fun"
print(x+y+z)

pythonisfun


In [24]:
# using the + operator to form sentence with a space charcters after is and python
x = "python "
y = "is "
z = "fun"
print(x,y,z)

python  is  fun


In [27]:
#type conversion
x = 2
y = 2.444
z = 23j
#
a = float(x)
b = int(y)
c = complex(x)

print(a)

print(c)

print(b)



2.0
(2+0j)
2


In [6]:
#format strings
age = 34
x = f"l am John,l am {age} years"
print(x)


l am John,l am 34 years


In [8]:
#Booleans represent one of two values: True or False
print(10 > 2)
print(10 == 10)
print(2 > 7)

True
True
False


In [ ]:
#PYTHON LISTS  Lists are used to store multiple items in a single variable.



In [10]:
width = 4.4
height = 7.9
area = width * height
print (area)

34.760000000000005


In [15]:
# SOLVING PROBLEMS
miles = 100
kilometres = miles * 1.609
print ("the value of kilometres is", kilometres)

the value of kilometres is 160.9


In [16]:
# the program to accept input from the user
#prompt the user to enter the width and height
width = eval(input("the width is:"))
height = eval(input("the height is:"))
area = width * height 
print("the area is:",area)


the width is: 23
the height is: 24


the area is: 552


In [19]:
#computing the average by prompting the user to enter input
number1 = eval(input("number1"))
number2 = eval(input("number2"))
number3 = eval(input("number3"))
number4 = eval(input("number4"))

average = (number1 + number2 + number3 + number4)/4
print ( "the average of four numbers is:", average)

number1 2
number2 3
number3 4
number4 5


the average of four numbers is: 3.5


In [12]:
#Swapping of values
a = 2
b = 3
a,b = b,a
print("a is:",a)
print("b is:",b)

a is: 3
b is: 2


In [ ]:
# Prompting a user to enter integer values float values cant be accepted


In [4]:
#simutaneous assignment while prompting the user to enter the input,  enter input in one line
num1, num2 ,num3 = eval(input("enter the numbers:"))
average = (num1 + num2 + num3)/3
print("the average of three numbers is:", average)

                              

enter the numbers: 1,2,3


the average of three numbers is: 2.0


In [18]:
#type conversion
y = 2.4 
print(int(y))

x = 34
print(float(x))

x = 34
print(complex(x))

x = 34
print(bool(x))

2
34.0
(34+0j)
True
